import { TreatmentCategory } from './types';

export const TREATMENT_CATEGORIES: TreatmentCategory[] = [
  {
    id: 'cleanup',
    name: 'Clean Up',
    slug: 'cleanup',
    fromPrice: '₹600',
    icon: 'sparkles',
    description: 'Deep cleansing treatments for radiant, refreshed skin',
    items: [
      { name: 'Fruit Cleanup', price: '₹600' },
      { name: 'Detan Cleanup', price: '₹1000' },
      { name: 'Advance Cleanup', price: '₹900' },
      { name: 'Aroma Cleanup', price: '₹1500' },
      { name: 'O3+ Cleanup', price: '₹1600' },
    ],
  },
  {
    id: 'detan',
    name: 'Detan',
    slug: 'detan',
    fromPrice: '₹300',
    icon: 'sun',
    description: 'Remove tan and restore your natural glow',
    items: [
      { name: 'Face', price: '₹500', pricePremium: '₹800' },
      { name: 'Neck', price: '₹500', pricePremium: '₹700' },
      { name: 'Back Neck', price: '₹600', pricePremium: '₹1000' },
      { name: 'Full Arms', price: '₹1000', pricePremium: '₹1500' },
      { name: 'Under Arms', price: '₹300', pricePremium: '₹500' },
      { name: 'Half Legs', price: '₹1000', pricePremium: '₹1500' },
      { name: 'Full Legs', price: '₹1500', pricePremium: '₹2000' },
      { name: 'Full Body', price: '₹3000', pricePremium: '₹4000' },
    ],
  },
  {
    id: 'bleach',
    name: 'Bleach',
    slug: 'bleach',
    fromPrice: '₹300',
    icon: 'droplets',
    description: 'Brighten and even out your skin tone',
    items: [
      { name: 'Face', price: '₹500' },
      { name: 'Neck', price: '₹300 / ₹400' },
      { name: 'Back Neck', price: '₹500+' },
      { name: 'Under Arms', price: '₹400' },
      { name: 'Full Arms', price: '₹500 / ₹1000' },
      { name: 'Half Arms', price: '₹500' },
      { name: 'Half Legs', price: '₹600' },
      { name: 'Full Legs', price: '₹1200' },
      { name: 'Full Body', price: '₹3000' },
    ],
  },
  {
    id: 'facials',
    name: 'Facials',
    slug: 'facials',
    fromPrice: '₹1200',
    icon: 'flower',
    description: 'Luxurious facials for every skin type',
    items: [
      { name: 'Fruit Facial', price: '₹1200' },
      { name: 'Wine Facial', price: '₹1500' },
      { name: 'Whitening Facial', price: '₹1500' },
      { name: 'Gold Facial', price: '₹1700' },
      { name: 'Pearl Facial', price: '₹1800' },
      { name: 'Diamond Facial', price: '₹2000' },
      { name: 'Chocolate Facial', price: '₹2500' },
      { name: "Nili's Signature Facial", price: '₹2800' },
    ],
  },
  {
    id: 'premium-treatment',
    name: 'Premium Treatment',
    slug: 'premium-treatment',
    fromPrice: '₹2800',
    icon: 'crown',
    description: 'Advanced skincare for visible, lasting results',
    items: [
      { name: 'Insta-Fair Facial', price: '₹2800' },
      { name: 'Anti-Acne Facial', price: '₹2800' },
      { name: 'Anti-Ageing Facial', price: '₹2800' },
      { name: 'O3+ Facial (Fairness)', price: '₹3000' },
      { name: 'O3+ Facial (Spot & Blemishes)', price: '₹3500' },
      { name: 'Nilis Premium Treatment', price: '₹3800' },
      { name: 'Double Whitening', price: '₹4000' },
    ],
  },
  {
    id: 'threading',
    name: 'Threading',
    slug: 'threading',
    fromPrice: '₹50',
    icon: 'scissors',
    description: 'Precise shaping for perfectly defined features',
    items: [
      { name: 'Eyebrow', price: '₹80' },
      { name: 'Upper Lips', price: '₹50' },
      { name: 'Forehead', price: '₹50' },
      { name: 'Chin', price: '₹50' },
      { name: 'Side Locks', price: '₹70' },
      { name: 'Neck', price: '₹50' },
      { name: 'Full Face', price: '₹250' },
    ],
  },
  {
    id: 'waxing',
    name: 'Waxing',
    slug: 'waxing',
    fromPrice: '₹100',
    icon: 'leaf',
    description: 'Smooth, silky skin with gentle waxing',
    items: [
      { name: 'Face', price: '₹500', pricePremium: '₹800' },
      { name: 'Upper Lip', price: '₹100', pricePremium: '₹180' },
      { name: 'Chin', price: '₹100', pricePremium: '₹180' },
      { name: 'Forehead', price: '₹120', pricePremium: '₹200' },
      { name: 'Jawline', price: '₹100', pricePremium: '₹150' },
      { name: 'Underarms', price: '₹200', pricePremium: '₹300' },
      { name: 'Side Locks', price: '₹150', pricePremium: '₹250' },
      { name: 'Neck', price: '₹160', pricePremium: '₹200' },
      { name: 'Blouse Line', price: '₹300', pricePremium: '₹500' },
      { name: 'Half Legs', price: '₹600', pricePremium: '₹700' },
      { name: 'Full Legs', price: '₹800', pricePremium: '₹1000' },
      { name: 'Half Arms', price: '₹500', pricePremium: '₹600' },
      { name: 'Full Arms', price: '₹600', pricePremium: '₹700' },
      { name: 'Full Body', price: '₹3500', pricePremium: '₹4500' },
      { name: 'Brazilian', price: '₹3000', pricePremium: '₹3500' },
    ],
  },
  {
    id: 'polishing',
    name: 'Polishing',
    slug: 'polishing',
    fromPrice: '₹700',
    icon: 'polishing',
    description: 'Exfoliate and polish for silky smooth skin',
    items: [
      { name: 'Neck', price: '₹1000' },
      { name: 'Under Arms', price: '₹700' },
      { name: 'Half Arms', price: '₹750' },
      { name: 'Full Arms', price: '₹1500' },
      { name: 'Half Legs', price: '₹1500' },
      { name: 'Full Legs', price: '₹2000' },
      { name: 'Full Body', price: '₹4000' },
    ],
  },
  {
    id: 'pedicure-manicure',
    name: 'Pedicure / Manicure',
    slug: 'pedicure-manicure',
    fromPrice: '₹800',
    icon: 'hand',
    description: 'Pamper your hands and feet with our signature treatments',
    items: [
      { name: 'Normal', price: '₹1000', pricePremium: '₹800' },
      { name: "Nili's Signature", price: '₹1500', pricePremium: '₹1200' },
      { name: 'Rose Pedicure', price: '₹1800', pricePremium: '₹1500' },
      { name: 'Bubble Gum', price: '₹2500', pricePremium: '₹2000' },
      { name: 'Chocolate', price: '₹1800', pricePremium: '₹1500' },
      { name: 'Premium', price: '₹2800', pricePremium: '₹2500' },
      { name: 'Ice Cream', price: '₹2200', pricePremium: '₹2000' },
      { name: 'Crystal', price: '₹1800', pricePremium: '₹1500' },
    ],
  },
  {
    id: 'hair-cut-women',
    name: 'Hair Cut (Women)',
    slug: 'hair-cut-women',
    fromPrice: '₹400',
    icon: 'scissors',
    description: 'Expert cuts and styling for every look',
    items: [
      { name: 'Regular Haircut', price: '₹500' },
      { name: 'Professional Hair Cut', price: '₹1000' },
      { name: 'Baby Hair Cut', price: '₹500' },
      { name: 'Kids Hair Cut (Normal)', price: '₹400' },
      { name: 'Kids Hair Cut (Professional)', price: '₹800' },
      { name: 'Hair Wash (Shampoo + Conditioning)', price: '₹600' },
      { name: 'Blow Dry', price: '₹400' },
      { name: 'Professional Styling', price: '₹800+' },
      { name: 'Temporary Ironing', price: '₹1000+' },
    ],
  },
  {
    id: 'hair-colour-women',
    name: 'Hair Colour (Women)',
    slug: 'hair-colour-women',
    fromPrice: '₹500',
    icon: 'palette',
    description: 'From subtle highlights to bold transformations',
    items: [
      { name: 'Root Touch-up', price: '₹1500' },
      { name: 'Global Colour', price: '₹3500+' },
      { name: 'Streaks', price: '₹500' },
      { name: 'Fashion Colour', price: '₹4500+' },
      { name: 'Global Highlights', price: '₹5000+' },
    ],
  },
  {
    id: 'hair-treatment-women',
    name: 'Hair Treatment (Women)',
    slug: 'hair-treatment-women',
    fromPrice: '₹2500',
    icon: 'flask',
    description: 'Professional treatments for healthy, beautiful hair',
    items: [
      { name: 'Dandruff Treatment', price: '₹2500' },
      { name: 'Hairfall Control', price: '₹2500' },
      { name: 'Frizz Hair Control', price: '₹3000' },
      { name: 'Smoothening / Straightening', price: '₹5000+' },
      { name: 'Keratin', price: '₹6500+' },
      { name: 'Botox', price: '₹8000+' },
    ],
  },
  {
    id: 'hair-spa-women',
    name: 'Hair Spa (Women)',
    slug: 'hair-spa-women',
    fromPrice: '₹1500',
    icon: 'wind',
    description: 'Rejuvenate and nourish your hair deeply',
    items: [
      { name: 'Hair Spa', price: '₹1500' },
      { name: 'Smoothening Spa', price: '₹2000' },
      { name: 'Kera Smooth Spa', price: '₹2500' },
    ],
  },
  {
    id: 'head-massage',
    name: 'Head Massage',
    slug: 'head-massage',
    fromPrice: '₹300',
    icon: 'heart',
    description: 'Relaxing massage therapy for total wellness',
    items: [
      { name: 'Head Massage', price: '₹500' },
      { name: 'Olive Oil Massage', price: '₹600' },
      { name: 'Aroma Oil Massage', price: '₹700' },
      { name: 'Deep Oil Conditioning', price: '₹1000' },
      { name: 'Hair Wash', price: '₹300' },
      { name: 'Foot Massage', price: '₹500' },
    ],
  },
  {
    id: 'bridal',
    name: 'Bridal Package & Makeup',
    slug: 'bridal',
    fromPrice: '₹2000',
    icon: 'heart',
    description: 'Complete bridal beauty for your special day',
    items: [
      { name: 'Bridal Package (A + B)', price: '₹25,000' },
      { name: '(A) Pre-Bridal Package (5 Days Prior)', price: '₹17,000' },
      { name: '(B) Wedding Day Package', price: '₹8000' },
      { name: 'Bridal Makeup – Simple', price: '₹2000' },
      { name: 'Party Makeup', price: '₹3000' },
      { name: 'Bridal (Function Makeup)', price: '₹5000' },
    ],
  },
  {
    id: 'nail-extension',
    name: 'Nail Extension',
    slug: 'nail-extension',
    fromPrice: '',
    icon: 'hand',
    description: 'Express yourself with stunning nail art and extensions',
    items: [
      { name: 'Nail Extension with Colour', price: '' },
      { name: 'Nail Extension with French', price: '' },
      { name: 'Nail Extension with Design', price: '' },
      { name: 'Acrylic Nail Extension', price: '' },
      { name: 'Nail Refilling', price: '' },
      { name: 'Refilling Breakout', price: '' },
      { name: 'Nail Extension + Chrome Art', price: '' },
      { name: 'Glitter Per Finger', price: '' },
      { name: 'Per Stones', price: '' },
      { name: 'Extension with Ombre', price: '' },
      { name: 'Natural Nail Paint', price: '' },
      { name: 'Natural Nail with French', price: '' },
      { name: 'Nail Overlay', price: '' },
      { name: '3D Nail Art', price: '' },
      { name: 'Nail Extension Removal', price: '' },
      { name: 'Gel Paint Removal', price: '' },
    ],
  },
  {
    id: 'eyelash-extension',
    name: 'Eyelash Extension',
    slug: 'eyelash-extension',
    fromPrice: '',
    icon: 'eyelash',
    description: 'Glamorous lash enhancements for every occasion',
    items: [
      { name: 'Eyelash Removal', price: '' },
      { name: 'Eyelash Extension Refilling', price: '' },
      { name: 'Classic Eyelash', price: '' },
      { name: '2D Eyelash', price: '' },
      { name: '3D Full Volume', price: '' },
    ],
  },
  // ─── MEN'S CATEGORIES ───
  {
    id: 'men-haircut',
    name: 'Hair Cut (Men)',
    slug: 'men-haircut',
    fromPrice: '',
    icon: 'scissors',
    description: 'Expert cuts and grooming for men',
    gender: 'men',
    items: [
      { name: 'Normal Hair Cut', price: '' },
      { name: 'Professional Hair Cut', price: '' },
      { name: 'Beard Styling', price: '' },
      { name: 'Beard Trimming', price: '' },
      { name: 'Shave', price: '' },
      { name: 'Hair Wash', price: '' },
      { name: 'Hair Styling', price: '' },
      { name: 'Kids Hair Cut', price: '' },
    ],
  },
  {
    id: 'men-hair-colour',
    name: 'Hair Colour (Men)',
    slug: 'men-hair-colour',
    fromPrice: '',
    icon: 'palette',
    description: 'From subtle touch-ups to bold colour transformations',
    gender: 'men',
    items: [
      { name: 'Hair Colour', price: '' },
      { name: 'Beard Colour', price: '' },
      { name: 'Streak', price: '' },
      { name: 'Highlights', price: '' },
      { name: 'Fashion Colour', price: '' },
    ],
  },
  {
    id: 'men-hair-treatment',
    name: 'Hair Treatment (Men)',
    slug: 'men-hair-treatment',
    fromPrice: '',
    icon: 'flask',
    description: 'Professional treatments for healthy, strong hair',
    gender: 'men',
    items: [
      { name: 'Nourishing Hair Spa', price: '' },
      { name: 'Dandruff Treatment', price: '' },
      { name: 'Hair Fall Control', price: '' },
      { name: 'Keratin', price: '' },
      { name: 'Smoothening', price: '' },
      { name: 'Straightening', price: '' },
    ],
  },
  {
    id: 'men-hair-spa',
    name: 'Hair Spa (Men)',
    slug: 'men-hair-spa',
    fromPrice: '',
    icon: 'wind',
    description: 'Rejuvenate and nourish your hair deeply',
    gender: 'men',
    items: [
      { name: 'Hair Spa', price: '' },
      { name: 'Smoothening Spa', price: '' },
      { name: 'Kera Spa', price: '' },
    ],
  },
  {
    id: 'men-detan',
    name: 'Detan (Men)',
    slug: 'men-detan',
    fromPrice: '',
    icon: 'sun',
    description: 'Remove tan and restore your natural glow',
    gender: 'men',
    items: [
      { name: 'Face', price: '' },
      { name: 'Full Neck', price: '' },
      { name: 'Back Neck', price: '' },
      { name: 'Full Arms', price: '' },
      { name: 'Full Legs', price: '' },
      { name: 'Full Body', price: '' },
    ],
  },
  {
    id: 'men-cleanup',
    name: 'Clean Up (Men)',
    slug: 'men-cleanup',
    fromPrice: '',
    icon: 'sparkles',
    description: 'Deep cleansing treatments for refreshed skin',
    gender: 'men',
    items: [
      { name: 'Fruit Cleanup', price: '' },
      { name: 'Detan Cleanup', price: '' },
      { name: 'Advance Cleanup', price: '' },
      { name: 'Aroma Cleanup', price: '' },
      { name: 'O3+ Cleanup', price: '' },
    ],
  },
  {
    id: 'men-bleach',
    name: 'Bleach (Men)',
    slug: 'men-bleach',
    fromPrice: '',
    icon: 'droplets',
    description: 'Brighten and even out your skin tone',
    gender: 'men',
    items: [
      { name: 'Face', price: '' },
      { name: 'Neck', price: '' },
      { name: 'Back Neck', price: '' },
      { name: 'Under Arms', price: '' },
      { name: 'Full Arms', price: '' },
      { name: 'Full Legs', price: '' },
      { name: 'Full Body', price: '' },
    ],
  },
  {
    id: 'men-facials',
    name: 'Facials (Men)',
    slug: 'men-facials',
    fromPrice: '',
    icon: 'flower',
    description: 'Luxurious facials for every skin type',
    gender: 'men',
    items: [
      { name: 'Fruit Facial', price: '' },
      { name: 'Wine Facial', price: '' },
      { name: 'Whitening Facial', price: '' },
      { name: 'Gold Facial', price: '' },
      { name: 'Pearl Facial', price: '' },
      { name: 'Diamond Facial', price: '' },
      { name: 'Chocolate Facial', price: '' },
      { name: "Nili's Signature Facial", price: '' },
    ],
  },
  {
    id: 'men-premium',
    name: 'Premium Treatment (Men)',
    slug: 'men-premium',
    fromPrice: '',
    icon: 'crown',
    description: 'Advanced skincare for visible, lasting results',
    gender: 'men',
    items: [
      { name: 'Insta-Fair Facial', price: '' },
      { name: 'Anti-Acne Facial', price: '' },
      { name: 'Anti-Ageing Facial', price: '' },
      { name: 'O3+ Facial (Fairness)', price: '' },
      { name: 'O3+ Facial (Spot & Blemishes)', price: '' },
      { name: "Nili's Premium Treatment", price: '' },
      { name: 'Double Whitening', price: '' },
    ],
  },
  {
    id: 'men-pedicure-manicure',
    name: 'Pedicure / Manicure (Men)',
    slug: 'men-pedicure-manicure',
    fromPrice: '',
    icon: 'hand',
    description: 'Pamper your hands and feet with signature treatments',
    gender: 'men',
    items: [
      { name: 'Normal Pedicure', price: '' },
      { name: 'Normal Manicure', price: '' },
      { name: "Nili's Signature Pedicure", price: '' },
      { name: "Nili's Signature Manicure", price: '' },
      { name: 'Rose Pedicure', price: '' },
      { name: 'Bubble Gum Pedicure', price: '' },
      { name: 'Chocolate Pedicure', price: '' },
      { name: 'Premium Pedicure', price: '' },
      { name: 'Ice Cream Pedicure', price: '' },
      { name: 'Crystal Pedicure', price: '' },
    ],
  },
  {
    id: 'men-polishing',
    name: 'Polishing (Men)',
    slug: 'men-polishing',
    fromPrice: '',
    icon: 'polishing',
    description: 'Exfoliate and polish for silky smooth skin',
    gender: 'men',
    items: [
      { name: 'Neck', price: '' },
      { name: 'Under Arms', price: '' },
      { name: 'Half Arms', price: '' },
      { name: 'Full Arms', price: '' },
      { name: 'Half Legs', price: '' },
      { name: 'Full Legs', price: '' },
      { name: 'Full Body', price: '' },
    ],
  },
  {
    id: 'men-head-massage',
    name: 'Head Massage (Men)',
    slug: 'men-head-massage',
    fromPrice: '',
    icon: 'heart',
    description: 'Relaxing massage therapy for total wellness',
    gender: 'men',
    items: [
      { name: 'Head Massage', price: '' },
      { name: 'Olive Oil Massage', price: '' },
      { name: 'Aroma Oil Massage', price: '' },
      { name: 'Deep Oil Conditioning', price: '' },
      { name: 'Hair Wash', price: '' },
      { name: 'Foot Massage', price: '' },
    ],
  },
];
